theme = "apollo"
# The URL the site will be built for
base_url = "https://pes-bca.pages.dev/"
title = "BCA | Study Materials"
description = "Organized collection of study materials for BCA '25 1st Sem"
build_search_index = false
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
theme = "dark"
toc = true
use_cdn = false
repo_url = "https://github.com/lalithbseervi/notes/"
dynamic_note = true
sw_version = "9f32c6e"

generate_sitemap = true
ignore = ["offline"]

menu = [
    { name = "Posts", url = "/posts", weight = 1 },
    { name = "Download PDFs", url = "/download", weight = 2 },
    { name = "Upload PDFs", url = "/upload", weight = 3 },
    { name = "Status", url = "/status", weight = 4 },
    { name = "Feedback", url = "/contribute", weight = 5 }
]

socials = [
  { name = "github", url = "https://github.com/", icon = "github" },
]

[extra.tags]
sort_by = "page_count"         # e.g. name, page_count
reverse = true
